create database DuAn1
go 
use DuAn1
go
--KHACHHANG->NHANVIEN->VOUCHER->PHUONGTHUCTHANHTOAN->
CREATE TABLE KHACHHANG (
    IDKhacHang INT identity(1,1) PRIMARY KEY NOT NULL,
	MaKhachHang NVARCHAR(50) NOT NULL,
	TenKhachHang NVARCHAR(50) NOT NULL,
	SoDienThoai INT NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	GioiTinh NVARCHAR(20) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL

);

CREATE TABLE NHANVIEN (
	IDNhanVien INT identity(1,1) PRIMARY KEY NOT NULL,
	MaNhanVien NVARCHAR(50) NOT NULL,
	TenNhanVien NVARCHAR(50) NOT NULL,
	GioiTinh NVARCHAR(20) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	ChucVu NVARCHAR(50) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	SoDienThoai INT NOT NULL,
	TaiKhoan NVARCHAR(50) NOT NULL,
	MatKhau INT NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL

);
CREATE TABLE VOUCHER (
	IDVoucher INT identity(1,1) PRIMARY KEY NOT NULL,
	MaVoucher NVARCHAR(50) NOT NULL,
	PhanTramGiamGia DECIMAL(5,2) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL

);
CREATE TABLE XUATXU (
	IDXuatXu INT identity(1,1) PRIMARY KEY NOT NULL,
	TenXuatSu NVARCHAR(50) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL
);

CREATE TABLE NONGDO (
	IDNongDo INT identity(1,1) PRIMARY KEY NOT NULL,
	TenNongDo NVARCHAR(50) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL
);

CREATE TABLE NHOMHUONG (
	IDNhomHuong INT identity(1,1) PRIMARY KEY NOT NULL,
	TenNhomHuong NVARCHAR(50) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL
);
CREATE TABLE PHUONGTHUCTHANHTOAN (
	IDPhuongThucThanhToan INT identity(1,1) PRIMARY KEY NOT NULL,
	TenPhuongThucThanhToan NVARCHAR(50) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL

);
CREATE TABLE THUONGHIEU (
	IDThuongHieu INT identity(1,1) PRIMARY KEY NOT NULL,
	MoTa NVARCHAR(50) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL
);
CREATE TABLE SANPHAM (
	IDNuocHoa INT identity(1,1) PRIMARY KEY NOT NULL, 
	IDThuongHieu INT NOT NULL,
	FOREIGN KEY (IDThuongHieu) REFERENCES THUONGHIEU(IDThuongHieu),
	TenSanPham NVARCHAR(50) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL
);
CREATE TABLE CHITIETSANPHAM (
	IDSanPhamChiTiet INT identity(1,1) PRIMARY KEY NOT NULL,
	IDNuocHoa int not null,
	IDXuatXu int not null,
	IDNongDo int not null,
	IDNhomHuong int not null,
	FOREIGN KEY (IDNuocHoa) REFERENCES SANPHAM(IDNuocHoa),
	FOREIGN KEY (IDXuatXu) REFERENCES XUATXU(IDXuatXu),
	FOREIGN KEY (IDNongDo) REFERENCES NONGDO(IDNongDo),
	FOREIGN KEY (IDNhomHuong) REFERENCES NHOMHUONG(IDNhomHuong),
	DoToaHuong NVARCHAR(50) NOT NULL,
	thoiGianLenDung DATETIME NOT NULL,
	NamPhatHanh DATE NOT NULL,
	DungTich INT NOT NULL,
LuuHuong DATETIME NOT NULL

);


CREATE TABLE HOADON (
	IDHoaDon INT identity(1,1) PRIMARY KEY NOT NULL,
	IDKhacHang int not null,
	IDNhanVien int not null,
	IDPhuongThucThanhToan int not null,
	IDVoucher int not null,
	FOREIGN KEY(IDKhacHang) REFERENCES KHACHHANG(IDKhacHang),
	FOREIGN KEY(IDNhanVien) REFERENCES NHANVIEN(IDNhanVien),
	FOREIGN KEY(IDPhuongThucThanhToan) REFERENCES PHUONGTHUCTHANHTOAN(IDPhuongThucThanhToan),
	FOREIGN KEY(IDVoucher) REFERENCES VOUCHER(IDVoucher),

	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL--0:dã h?y,1:ch? xác nh?n, 2:Ðang giao,3:Ðã giao

);

CREATE TABLE HOADONCHITIET (
	IDHoaDonChiTiet INT identity(1,1) PRIMARY KEY NOT NULL,
	IDHoaDon int not null,
	IDSanPhamChiTiet int not null,
	FOREIGN KEY(IDHoaDon) REFERENCES HOADON(IDHoaDon),
	FOREIGN KEY(IDSanPhamChiTiet) REFERENCES CHITIETSANPHAM(IDSanPhamChiTiet),
	TenSanPham NVARCHAR(50) NOT NULL,
	GiaBan MONEY NOT NULL,
	SoLuong INT NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgaySua DATETIME NOT NULL,
	TrangThai INT NOT NULL

);

select * from THUONGHIEU